steps:
  # ============================================
  # STAGE 1: CODE QUALITY & SECURITY
  # ============================================
  
  # Step 0: Lint Code (flake8)
  # Checks Python code style and formatting
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install flake8
        flake8 app/ --max-line-length=120 --ignore=E501,W503 --statistics
    id: 'lint'

  # Step 1: Security Scan - Python Code (Bandit)
  # Scans for common security issues like hardcoded passwords,
  # SQL injection, insecure functions, etc.
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install bandit
        echo "Running Bandit security scan..."
        bandit -r app/ -ll -ii --format json --output bandit-report.json || true
        bandit -r app/ -ll -ii --format txt
        echo "Security scan complete!"
    id: 'security-scan'
    waitFor: ['lint']

  # Step 2: Run Tests (pytest)
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r app/requirements.txt
        cd app && python -m pytest ../tests/ -v --tb=short
    id: 'test'
    waitFor: ['security-scan']

  # ============================================
  # STAGE 2: BUILD & SCAN CONTAINER
  # ============================================

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'app/Dockerfile'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/todo-app:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/todo-app:latest'
      - 'app'
    waitFor: ['test']
    id: 'build'

  # Step 4: Container Security Scan (Trivy)
  # Scans Docker image for known vulnerabilities (CVEs)
  # Checks OS packages, Python dependencies, etc.
  - name: 'aquasec/trivy:latest'
    args:
      - 'image'
      - '--exit-code'
      - '0'
      - '--severity'
      - 'HIGH,CRITICAL'
      - '--format'
      - 'table'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/todo-app:$COMMIT_SHA'
    id: 'container-scan'
    waitFor: ['build']

  # ============================================
  # STAGE 3: DEPLOY
  # ============================================

  # Step 5: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/todo-app'
    waitFor: ['container-scan']
    id: 'push'

  # Step 6: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/todo-app:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
    waitFor: ['push']

# Substitution variables (can be overridden at build time)
substitutions:
  _REGION: 'us-east1'
  _REPO_NAME: 'cloud-run-source-deploy'
  _SERVICE_NAME: 'devops-google'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Images to be pushed
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/todo-app:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/todo-app:latest'
